name: Docker Image CI

on:
  push:
    branches: [ "contrib" ]
  pull_request:
    branches: [ "contrib" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend Docker image
      working-directory: ./backend
      run: docker build . --file Dockerfile --tag app-pengabdian-backend:$(date +%s)
