name: Test CI

on:
  push:
    branches: [ "contrib" ]
  pull_request:
    branches: [ "contrib" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install
      working-directory: ./backend
      run: make install

    - name: create .env
      working-directory: ./backend
      run: echo "SECRET_KEY=somerandom123456789" > .env

    - name: test
      working-directory: ./backend
      run: make testing
